In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv('TelecomChurn.csv')

In [3]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85         29.85     No  
1               Mailed check          56.95       1889.50     No  
2               Mailed check          53.85        108.15    Yes  
3  Bank transfer (automatic)          42.30       1840.75     No  
4           Electronic check          70.70        151.65    Yes  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7032 non-null   object 
 1   gender            7032 non-null   object 
 2   SeniorCitizen     7032 non-null   int64  
 3   Partner           7032 non-null   object 
 4   Dependents        7032 non-null   object 
 5   tenure            7032 non-null   int64  
 6   PhoneService      7032 non-null   object 
 7   MultipleLines     7032 non-null   object 
 8   InternetService   7032 non-null   object 
 9   OnlineSecurity    7032 non-null   object 
 10  OnlineBackup      7032 non-null   object 
 11  DeviceProtection  7032 non-null   object 
 12  TechSupport       7032 non-null   object 
 13  StreamingTV       7032 non-null   object 
 14  StreamingMovies   7032 non-null   object 
 15  Contract          7032 non-null   object 
 16  PaperlessBilling  7032 non-null   object 


In [5]:
df.drop('customerID',inplace=True,axis=1)

In [6]:
df.head(2)

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   

  PaperlessBilling     PaymentMethod  MonthlyCharges  TotalCharges Churn  
0              Yes  Electronic check           29.85         29.85    No  
1               No      Mailed check           56.95       1889.50    No

In [7]:
df['Partner'].value_counts()

No     3639
Yes    3393
Name: Partner, dtype: int64

In [8]:
df['Dependents'].value_counts()

No     4933
Yes    2099
Name: Dependents, dtype: int64

In [9]:
df['PhoneService'].value_counts()

Yes    6352
No      680
Name: PhoneService, dtype: int64

In [10]:
df['MultipleLines'].value_counts()

No                  3385
Yes                 2967
No phone service     680
Name: MultipleLines, dtype: int64

In [11]:
df['InternetService'].value_counts()

Fiber optic    3096
DSL            2416
No             1520
Name: InternetService, dtype: int64

In [12]:
df['OnlineSecurity'].value_counts()

No                     3497
Yes                    2015
No internet service    1520
Name: OnlineSecurity, dtype: int64

In [13]:
df['OnlineBackup'].value_counts()

No                     3087
Yes                    2425
No internet service    1520
Name: OnlineBackup, dtype: int64

In [14]:
df['DeviceProtection'].value_counts()

No                     3094
Yes                    2418
No internet service    1520
Name: DeviceProtection, dtype: int64

In [15]:
df['TechSupport'].value_counts()

No                     3472
Yes                    2040
No internet service    1520
Name: TechSupport, dtype: int64

In [16]:
df['StreamingTV'].value_counts()

No                     2809
Yes                    2703
No internet service    1520
Name: StreamingTV, dtype: int64

In [17]:
df['StreamingMovies'].value_counts()

No                     2781
Yes                    2731
No internet service    1520
Name: StreamingMovies, dtype: int64

In [18]:
df['Contract'].value_counts()

Month-to-month    3875
Two year          1685
One year          1472
Name: Contract, dtype: int64

In [19]:
df['PaperlessBilling'].value_counts()

Yes    4168
No     2864
Name: PaperlessBilling, dtype: int64

In [20]:
df['PaymentMethod'].value_counts()

Electronic check             2365
Mailed check                 1604
Bank transfer (automatic)    1542
Credit card (automatic)      1521
Name: PaymentMethod, dtype: int64

In [21]:
df['Churn'].value_counts()

No     5163
Yes    1869
Name: Churn, dtype: int64

In [22]:
X=df.drop('Churn',axis=1)

In [23]:
y=df['Churn']

In [24]:
X=pd.get_dummies(X,drop_first=True)

In [25]:
X.shape

(7032, 30)

In [26]:
X.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
ss=StandardScaler()

In [31]:
X_train=ss.fit_transform(X_train)

In [32]:
X_test=ss.transform(X_test)

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
model=LogisticRegression()

In [35]:
model.fit(X_train,y_train)

LogisticRegression()

In [36]:
predict1=model.predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix,classification_report

In [38]:
print(confusion_matrix(y_test,predict1))

[[1377  172]
 [ 261  300]]


In [39]:
print(classification_report(y_test,predict1))

              precision    recall  f1-score   support

          No       0.84      0.89      0.86      1549
         Yes       0.64      0.53      0.58       561

    accuracy                           0.79      2110
   macro avg       0.74      0.71      0.72      2110
weighted avg       0.79      0.79      0.79      2110



In [40]:
from sklearn.svm import SVC

In [41]:
model=SVC()

In [42]:
model.fit(X_train,y_train)

SVC()

In [43]:
predict2=model.predict(X_test)

In [44]:
print(confusion_matrix(y_test,predict2))

[[1401  148]
 [ 290  271]]


In [45]:
print(classification_report(y_test,predict2))

              precision    recall  f1-score   support

          No       0.83      0.90      0.86      1549
         Yes       0.65      0.48      0.55       561

    accuracy                           0.79      2110
   macro avg       0.74      0.69      0.71      2110
weighted avg       0.78      0.79      0.78      2110



In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
model=RandomForestClassifier()

In [48]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [49]:
predict3=model.predict(X_test)

In [50]:
print(confusion_matrix(y_test,predict3))

[[1389  160]
 [ 288  273]]


In [51]:
print(classification_report(y_test,predict3))

              precision    recall  f1-score   support

          No       0.83      0.90      0.86      1549
         Yes       0.63      0.49      0.55       561

    accuracy                           0.79      2110
   macro avg       0.73      0.69      0.71      2110
weighted avg       0.78      0.79      0.78      2110



In [52]:
from xgboost import XGBClassifier

C:\Users\kriti\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [53]:
model=XGBClassifier()

In [54]:
model.fit(X_train,y_train)

C:\Users\kriti\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[23:43:22] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [55]:
predict4=model.predict(X_test)

In [56]:
print(confusion_matrix(y_test,predict4))

[[1348  201]
 [ 284  277]]


In [57]:
print(classification_report(y_test,predict4))

              precision    recall  f1-score   support

          No       0.83      0.87      0.85      1549
         Yes       0.58      0.49      0.53       561

    accuracy                           0.77      2110
   macro avg       0.70      0.68      0.69      2110
weighted avg       0.76      0.77      0.76      2110



In [61]:
from imblearn.combine import SMOTETomek

smt = SMOTETomek(sampling_strategy='auto')
X_smt, y_smt = smt.fit_resample(X, y)

In [65]:
y_smt.value_counts()

No     4738
Yes    4738
Name: Churn, dtype: int64

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X_smt, y_smt, test_size=0.30, random_state=42)

In [67]:
ss=StandardScaler()

In [68]:
X_train=ss.fit_transform(X_train)

In [69]:
X_test=ss.transform(X_test)

In [70]:
model=LogisticRegression()

In [71]:
model.fit(X_train,y_train)

LogisticRegression()

In [72]:
predict1=model.predict(X_test)

In [73]:
print(confusion_matrix(y_test,predict1))

[[1195  262]
 [ 191 1195]]


In [74]:
print(classification_report(y_test,predict1))

              precision    recall  f1-score   support

          No       0.86      0.82      0.84      1457
         Yes       0.82      0.86      0.84      1386

    accuracy                           0.84      2843
   macro avg       0.84      0.84      0.84      2843
weighted avg       0.84      0.84      0.84      2843



In [75]:
model=SVC()
model.fit(X_train,y_train)
predict2=model.predict(X_test)
print(confusion_matrix(y_test,predict2))
print(classification_report(y_test,predict2))

[[1207  250]
 [ 228 1158]]
              precision    recall  f1-score   support

          No       0.84      0.83      0.83      1457
         Yes       0.82      0.84      0.83      1386

    accuracy                           0.83      2843
   macro avg       0.83      0.83      0.83      2843
weighted avg       0.83      0.83      0.83      2843



In [76]:
model=RandomForestClassifier()
model.fit(X_train,y_train)
predict3=model.predict(X_test)
print(confusion_matrix(y_test,predict3))
print(classification_report(y_test,predict3))

[[1229  228]
 [ 177 1209]]
              precision    recall  f1-score   support

          No       0.87      0.84      0.86      1457
         Yes       0.84      0.87      0.86      1386

    accuracy                           0.86      2843
   macro avg       0.86      0.86      0.86      2843
weighted avg       0.86      0.86      0.86      2843



In [77]:
model=XGBClassifier()
model.fit(X_train,y_train)
predict4=model.predict(X_test)
print(confusion_matrix(y_test,predict4))
print(classification_report(y_test,predict4))

C:\Users\kriti\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[23:51:49] WARNING: ..\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[[1246  211]
 [ 188 1198]]
              precision    recall  f1-score   support

          No       0.87      0.86      0.86      1457
         Yes       0.85      0.86      0.86      1386

    accuracy                           0.86      2843
   macro avg       0.86      0.86      0.86      2843
weighted avg       0.86      0.86      0.86      2843

